baseURL = "https://dweezy.net/"
languageCode = "en-us"
title = "Daniel Wyleczuk-Stern"
theme = "hugo-resume"

[params]
    firstName = "Daniel"
    lastName = "Wyleczuk-Stern"
    address = "Washington, DC"
    contactNote = "Principal Security Engineer"
    profileImage = "img/profile1.jpg"
    email = "dweezy.netsec@gmail.com"
    description = "Senior Network Security Engineer with experience in Penetration Testing, enterprise security framework design, and detection and response."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/danielwyleczukstern/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/dweezy-netsec"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/Daniel_Cybersec"

[params.google.analytics]
    trackerID = "XX-123446-01"
